import { defineStore } from 'pinia';import { computed,ref,watch } from 'vue';import { useConnectionStore } from './connection';import { useSessionsStore } from './sessions'
export interface ChatMessage{id:string;type:'user'|'assistant';content:string;reasoning?:string;model?:string;provider?:string;thinking?:string;usage?:any;duration_ms?:number;ttft_ms?:number;finish?:string;error?:string;status?:'streaming'|'done'}
class SSE{buf='';feed(s:string){this.buf+=s.replace(/\r\n/g,'\n');const out:{event:string;data:string}[]=[];let i;while((i=this.buf.indexOf('\n\n'))>=0){const b=this.buf.slice(0,i);this.buf=this.buf.slice(i+2);let event='message';const data:string[]=[];for(const l of b.split('\n')){if(l.startsWith('event:'))event=l.slice(6).trim();if(l.startsWith('data:'))data.push(l.slice(5).trimStart())}if(data.length)out.push({event,data:data.join('\n')})}return out}}
export const useChatStore=defineStore('chat',()=>{const c=useConnectionStore(),s=useSessionsStore();const messages=ref<ChatMessage[]>([]),input=ref(''),modelKey=ref(''),thinking=ref('off'),streaming=ref(false),notice=ref('');let abort:AbortController|undefined;let generation=0
const model=computed(()=>c.models.find(x=>x.key===modelKey.value));const thinkingLevels=computed(()=>model.value?.thinking_levels?.length?model.value.thinking_levels:['off']);watch(()=>c.models,()=>{if(!c.models.some(x=>x.key===modelKey.value))modelKey.value=c.defaultModelKey},{deep:true,immediate:true});watch(model,()=>{if(!thinkingLevels.value.includes(thinking.value))thinking.value=thinkingLevels.value.includes('off')?'off':thinkingLevels.value[0]},{immediate:true})
async function openSession(id:string){generation++;abort?.abort();abort=undefined;streaming.value=false;s.select(id);messages.value=[];notice.value='';const token=generation;try{const r=await fetch(`${c.serverUrl}/api/sessions/${encodeURIComponent(id)}/messages`,{cache:'no-store'});if(!r.ok)throw new Error(`读取消息失败 (${r.status})`);const v=await r.json();if(token===generation&&s.currentId===id)messages.value=v}catch(e:any){if(token===generation)notice.value=e?.message||String(e)}}
function newChat(){generation++;abort?.abort();abort=undefined;streaming.value=false;s.fresh();messages.value=[];notice.value='';input.value=''}
async function send(){const text=input.value.trim();if(!text||!modelKey.value||streaming.value)return;const token=++generation;let sid=s.currentId;const localUser:ChatMessage={id:`u-${crypto.randomUUID()}`,type:'user',content:text,status:'done'};const localAssistant:ChatMessage={id:`a-${crypto.randomUUID()}`,type:'assistant',content:'',reasoning:'',status:'streaming'};messages.value.push(localUser,localAssistant);input.value='';streaming.value=true;try{if(!sid){sid=(await s.create(text.slice(0,36))).id}abort=new AbortController();const r=await fetch(`${c.serverUrl}/api/sessions/${encodeURIComponent(sid)}/chat`,{method:'POST',headers:{'content-type':'application/json','accept':'text/event-stream'},body:JSON.stringify({message:text,model_key:modelKey.value,thinking:thinking.value}),signal:abort.signal});if(!r.ok)throw new Error((await r.text())||`发送失败 ${r.status}`);if(!r.body)throw new Error('没有流式响应');const rd=r.body.getReader(),dec=new TextDecoder(),parser=new SSE();while(true){const {done,value}=await rd.read();if(done)break;for(const ev of parser.feed(dec.decode(value,{stream:true}))){const d=JSON.parse(ev.data||'{}');if(ev.event==='ack'&&d.message?.id)localUser.id=d.message.id;else if(ev.event==='delta')localAssistant.content+=d.text||'';else if(ev.event==='reasoning')localAssistant.reasoning=(localAssistant.reasoning||'')+(d.text||'');else if(ev.event==='usage')localAssistant.usage=d;else if(ev.event==='ttft')localAssistant.ttft_ms=d.ms;else if(ev.event==='error')localAssistant.error=d.message;else if(ev.event==='done'){localAssistant.finish=d.finish;localAssistant.duration_ms=d.duration_ms;localAssistant.status='done';if(d.message_id)localAssistant.id=d.message_id}}}if(token===generation&&sid===s.currentId){const rr=await fetch(`${c.serverUrl}/api/sessions/${encodeURIComponent(sid)}/messages`,{cache:'no-store'});if(rr.ok)messages.value=await rr.json();await s.load().catch(()=>{})}}catch(e:any){if(e?.name!=='AbortError'){localAssistant.error=e?.message||String(e);localAssistant.status='done';notice.value=localAssistant.error}}finally{if(token===generation)streaming.value=false}}
async function stop(){if(!s.currentId)return;await fetch(`${c.serverUrl}/api/sessions/${encodeURIComponent(s.currentId)}/chat/cancel`,{method:'POST'}).catch(()=>{});abort?.abort();streaming.value=false}
return{messages,input,modelKey,thinking,model,thinkingLevels,streaming,notice,openSession,newChat,send,stop}})
